### PR TITLE
Add Babel support

### PR DESCRIPTION
**Pull request by plbrault**
Allow GraphQL function to be compiled using Babel.

Usage:

1. `npm install babel-preset-es2015 --save-dev`
2. Add this in `serverless.yml`:
```
custom:
  graphiql:
    babelOptions:
      presets: ['es2015']
```

### CODE REVIEW

**Comment by plbrault** [comment]
@bencooling Did you have the time to check this?

**Comment by bencooling** [comment]
@plbrault Sorry about the lateness I initially wasn't sure whether it was a plugin specific concern and whether it was outside of the specific problem this plugin was attempting to solve.

Is there a reason you declare the babel presets in the `serverless.yml` config file as opposed to a plugin cli option (my preference)? i.e.  

```bash
sls graphiql --babel es2015,stage-2
```

You could always alias long commands behind npm script like`npm run graphiql`, and within
package.json you could have something like 
```json
{
"graphiql": "sls graphiql --port 3000 --function myApi --babel es2015,stage-2"
}
```

**Comment by kevin-wolf** [comment]
@bencooling, @plbrault  any update on this?

**Comment by plbrault** [comment]
It is my turn to be sorry for the lateness! ;)

The reason why I originally chose to declare the babel presets in the `serverless.yml` file was because I based my implementation on this package: https://github.com/dherault/serverless-offline

However, I personally prefer this way, as it allows to refer to a `.babelrc` file that can also be used by the other plugins. For example:
```
custom:
  graphiql:
    babelOptions:
      presets: ${file(./.babelrc):presets}
  optimize:
    presets: ${file(./.babelrc):presets}
  serverless-offline:
    babelOptions:
      presets: ${file(./.babelrc):presets}
```

However, this is your repo, so I will let you choose the way that you prefer, and update my pull request accordingly. Another option would be to support the two ways (config parameter + cli option).

**Comment by bencooling** [comment]
If this is consistent with serverless-offline that settles it for me.

**Comment by bencooling** [comment]
Now available on npm with latest version `v0.3.0`.

**Pull request merged**
